name: Check the source code style

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    name: Check the source code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run lint:prettier
      - name: Lint
        run: npm run lint:js
